### ISSUE TITLE
prototyping, versioning, and janitorial cleanup

### ISSUE THREAD

**Issue by briceburg** [altairsix/eventsource#1]
@savaki  Hey I hope here is an appropriate place to ask --

Do you have any recommendations or tools in place for cleaning up after prototyping? E.g. removing the S3 archive and DynamoDB tables after testing an application and before switching to "production"? 

Also is there anything in place for versioning of the eventstream (e.g. if a schema changes -- or if we want to switch from a staging > production queue)

Thanks! I loved your gopherfest talk and missed out during the q/a.

**Comment by savaki** [comment]
Hey Brice, this is as good a place as any.

I would imagine that you'd probably want to leave the S3 archive and the DynamoDB tables around.  We have things arranged by environment so we have latest, staging, and production environments along with some temporary environments we create for things like performance testing.  To answer the question more directly, I haven't done anything on the S3 side as the S3 console is so easy to use.  For dynamodb, this package comes with a utility to setup/teardown the dynamodb table(s).

```
go run cmd/eventsource/main.go dynamodb create-table --name {table-name}
go run cmd/eventsource/main.go dynamodb delete-table --name {table-name}
``` 
As for versioning the event stream, Greg Young, has a new book coming out that talks about this sort of thing, https://leanpub.com/esversioning.  While you'd like to avoid it if possible (by having events stick to facts as much as possible and not including business rules in them), I agree the need to version exists.  I'll probably write something for it, but for now, it would be a matter of scanning through the S3 bucket and updating the contents and doing a scan of the dynamodb table to do the same thing.

**Comment by savaki** [comment]
Cool. I'd be interested in hear what you come up with.
