### ISSUE TITLE
gopherfest example does not work

### ISSUE THREAD

**Issue by delaneyj** [altairsix/eventsource#4]
Watch the talk and tried to run the [gopherfest ](https://github.com/altairsix/eventsource/blob/master/_examples/gopherfest/main.go) example, unfortunately got the error `file: 'github.com/altairsix/eventsource/_examples/gopherfest/main.go'
severity: 'Error'
message: 'undefined: eventsource.NewDispatcher'
at: '98,2'
source: ''`

Has the examples been checked for the against the latest revisions?

**Comment by eblanchette** [comment]
I think the Dispatcher was removed

https://github.com/altairsix/eventsource/commit/99c74dd1dc6e11d4ca305c6ef8d872a0df271b27

**Comment by delaneyj** [comment]
From what I can tell this commit is removing the dispatch call from repository, not removing the `NewDispatcher()` call from package.  Unfortunately, still not clear the right way to make the sample work properly.

**Comment by eblanchette** [comment]
You need to call .Apply on the repo .Dispatch has been deprecated.

**Comment by savaki** [comment]
Sorry guys and thanks for the updates.  I've merged the pull request so this won't be a problem for others.
